/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountPlanType {
    #[serde(rename = "Free")]
    Free,
    #[serde(rename = "Developer")]
    Developer,

}

impl ToString for AccountPlanType {
    fn to_string(&self) -> String {
        match self {
            Self::Free => String::from("Free"),
            Self::Developer => String::from("Developer"),
        }
    }
}

impl Default for AccountPlanType {
    fn default() -> AccountPlanType {
        Self::Free
    }
}




