/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountProvider {
    #[serde(rename = "GitHub")]
    GitHub,
    #[serde(rename = "DeviceFlow")]
    DeviceFlow,

}

impl ToString for AccountProvider {
    fn to_string(&self) -> String {
        match self {
            Self::GitHub => String::from("GitHub"),
            Self::DeviceFlow => String::from("DeviceFlow"),
        }
    }
}

impl Default for AccountProvider {
    fn default() -> AccountProvider {
        Self::GitHub
    }
}

