/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountPlan {
    #[serde(rename = "accountType", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<crate::models::AccountPlanType>,
    #[serde(rename = "cancelAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancel_at: Option<Option<String>>,
}

impl AccountPlan {
    pub fn new() -> AccountPlan {
        AccountPlan {
            account_type: None,
            cancel_at: None,
        }
    }
}


