/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiHealthStatus {
    #[serde(rename = "Healthy")]
    Healthy,
    #[serde(rename = "Unhealthy")]
    Unhealthy,
    #[serde(rename = "Degraded")]
    Degraded,

}

impl ToString for ApiHealthStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Healthy => String::from("Healthy"),
            Self::Unhealthy => String::from("Unhealthy"),
            Self::Degraded => String::from("Degraded"),
        }
    }
}

impl Default for ApiHealthStatus {
    fn default() -> ApiHealthStatus {
        Self::Healthy
    }
}




