/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppRequestCount {
    #[serde(rename = "start")]
    pub start: i64,
    #[serde(rename = "end")]
    pub end: i64,
    #[serde(rename = "interval")]
    pub interval: i32,
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "averagePerSecond")]
    pub average_per_second: f64,
    #[serde(rename = "points")]
    pub points: Vec<crate::models::AppRequestPoint>,
}

impl AppRequestCount {
    pub fn new(start: i64, end: i64, interval: i32, total: i64, average_per_second: f64, points: Vec<crate::models::AppRequestPoint>) -> AppRequestCount {
        AppRequestCount {
            start,
            end,
            interval,
            total,
            average_per_second,
            points,
        }
    }
}


