/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppDomainItem {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "validationStatus")]
    pub validation_status: crate::models::DomainValidationStatus,
}

impl AppDomainItem {
    pub fn new(name: String, validation_status: crate::models::DomainValidationStatus) -> AppDomainItem {
        AppDomainItem {
            name,
            validation_status,
        }
    }
}


