/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppRequestPointItem {
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "value")]
    pub value: i64,
}

impl AppRequestPointItem {
    pub fn new(timestamp: i64, value: i64) -> AppRequestPointItem {
        AppRequestPointItem {
            timestamp,
            value,
        }
    }
}

