/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppSummaryDto {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "storageId")]
    pub storage_id: String,
    #[serde(rename = "channels")]
    pub channels: Vec<models::AppChannelListItem>,
    #[serde(rename = "lastModified", skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<String>,
}

impl AppSummaryDto {
    pub fn new(id: uuid::Uuid, name: String, storage_id: String, channels: Vec<models::AppChannelListItem>) -> AppSummaryDto {
        AppSummaryDto {
            id,
            name,
            storage_id,
            channels,
            last_modified: None,
        }
    }
}

