/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppRequestCountItem {
    #[serde(rename = "start")]
    pub start: i64,
    #[serde(rename = "end")]
    pub end: i64,
    #[serde(rename = "interval")]
    pub interval: i32,
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "averagePerSecond")]
    pub average_per_second: f64,
    #[serde(rename = "points")]
    pub points: Vec<models::AppRequestPointItem>,
}

impl AppRequestCountItem {
    pub fn new(start: i64, end: i64, interval: i32, total: i64, average_per_second: f64, points: Vec<models::AppRequestPointItem>) -> AppRequestCountItem {
        AppRequestCountItem {
            start,
            end,
            interval,
            total,
            average_per_second,
            points,
        }
    }
}

