/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelItem {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "appId")]
    pub app_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "revisionSelectionStrategy")]
    pub revision_selection_strategy: crate::models::ChannelRevisionSelectionStrategy,
    #[serde(rename = "desiredStatus")]
    pub desired_status: String,
    #[serde(rename = "activeRevision", skip_serializing_if = "Option::is_none")]
    pub active_revision: Option<Box<crate::models::RevisionItem>>,
    #[serde(rename = "lastPublishAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_publish_at: Option<Option<String>>,
    #[serde(rename = "rangeRule", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub range_rule: Option<Option<String>>,
    #[serde(rename = "appSummary", skip_serializing_if = "Option::is_none")]
    pub app_summary: Option<Box<crate::models::AppSummaryDto>>,
    #[serde(rename = "environmentVariables")]
    pub environment_variables: Vec<crate::models::EnvironmentVariableItem>,
}

impl ChannelItem {
    pub fn new(id: uuid::Uuid, app_id: uuid::Uuid, name: String, domain: String, revision_selection_strategy: crate::models::ChannelRevisionSelectionStrategy, desired_status: String, environment_variables: Vec<crate::models::EnvironmentVariableItem>) -> ChannelItem {
        ChannelItem {
            id,
            app_id,
            name,
            domain,
            revision_selection_strategy,
            desired_status,
            active_revision: None,
            last_publish_at: None,
            range_rule: None,
            app_summary: None,
            environment_variables,
        }
    }
}


