/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelRevisionSelectionStrategyField {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<models::ChannelRevisionSelectionStrategy>,
}

impl ChannelRevisionSelectionStrategyField {
    pub fn new() -> ChannelRevisionSelectionStrategyField {
        ChannelRevisionSelectionStrategyField {
            value: None,
        }
    }
}

