/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTokenCommand {
    #[serde(rename = "providerCode", skip_serializing_if = "Option::is_none")]
    pub provider_code: Option<String>,
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<crate::models::AccountProvider>,
    #[serde(rename = "isMarketingEmailOn", skip_serializing_if = "Option::is_none")]
    pub is_marketing_email_on: Option<bool>,
}

impl CreateTokenCommand {
    pub fn new() -> CreateTokenCommand {
        CreateTokenCommand {
            provider_code: None,
            client_id: None,
            provider: None,
            is_marketing_email_on: None,
        }
    }
}


