/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateVariablePairCommand {
    #[serde(rename = "appId")]
    pub app_id: uuid::Uuid,
    #[serde(rename = "variable")]
    pub variable: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl CreateVariablePairCommand {
    pub fn new(app_id: uuid::Uuid, variable: String, value: String) -> CreateVariablePairCommand {
        CreateVariablePairCommand {
            app_id,
            variable,
            value,
        }
    }
}


