/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateKeyValuePairCommand {
    #[serde(rename = "appId")]
    pub app_id: uuid::Uuid,
    #[serde(rename = "storeName")]
    pub store_name: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl CreateKeyValuePairCommand {
    pub fn new(app_id: uuid::Uuid, store_name: String, key: String, value: String) -> CreateKeyValuePairCommand {
        CreateKeyValuePairCommand {
            app_id,
            store_name,
            key,
            value,
        }
    }
}


