/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateKeyValuePairCommand {
    #[serde(rename = "appId", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<uuid::Uuid>,
    #[serde(rename = "storeName", skip_serializing_if = "Option::is_none")]
    pub store_name: Option<String>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl CreateKeyValuePairCommand {
    pub fn new(key: String, value: String) -> CreateKeyValuePairCommand {
        CreateKeyValuePairCommand {
            app_id: None,
            store_name: None,
            key,
            value,
            label: None,
        }
    }
}


