/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAppCommand {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "storageId")]
    pub storage_id: String,
    #[serde(rename = "createDefaultDatabase", skip_serializing_if = "Option::is_none")]
    pub create_default_database: Option<bool>,
}

impl CreateAppCommand {
    pub fn new(name: String, storage_id: String) -> CreateAppCommand {
        CreateAppCommand {
            name,
            storage_id,
            create_default_database: None,
        }
    }
}


