/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Database {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(rename = "links")]
    pub links: Vec<crate::models::ResourceLabel>,
}

impl Database {
    pub fn new(name: String, links: Vec<crate::models::ResourceLabel>) -> Database {
        Database {
            name,
            default: None,
            links,
        }
    }
}


