/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabasesList {
    #[serde(rename = "databases")]
    pub databases: Vec<models::Database>,
}

impl DatabasesList {
    pub fn new(databases: Vec<models::Database>) -> DatabasesList {
        DatabasesList {
            databases,
        }
    }
}

