/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatabasesList {
    #[serde(rename = "databases")]
    pub databases: Vec<crate::models::Database>,
}

impl DatabasesList {
    pub fn new(databases: Vec<crate::models::Database>) -> DatabasesList {
        DatabasesList {
            databases,
        }
    }
}


