/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Database {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "default")]
    pub default: bool,
}

impl Database {
    pub fn new(name: String, default: bool) -> Database {
        Database {
            name,
            default,
        }
    }
}


