/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceCodeDetails {
    #[serde(rename = "clientName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_name: Option<Option<String>>,
}

impl DeviceCodeDetails {
    pub fn new() -> DeviceCodeDetails {
        DeviceCodeDetails {
            client_name: None,
        }
    }
}


