/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceCodeItem {
    #[serde(rename = "deviceCode")]
    pub device_code: String,
    #[serde(rename = "userCode")]
    pub user_code: String,
    #[serde(rename = "verificationUrl")]
    pub verification_url: String,
    #[serde(rename = "expiresIn")]
    pub expires_in: i64,
    #[serde(rename = "interval")]
    pub interval: i32,
}

impl DeviceCodeItem {
    pub fn new(device_code: String, user_code: String, verification_url: String, expires_in: i64, interval: i32) -> DeviceCodeItem {
        DeviceCodeItem {
            device_code,
            user_code,
            verification_url,
            expires_in,
            interval,
        }
    }
}

