/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Entry {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::Meta>>,
    #[serde(rename = "logLines", skip_serializing_if = "Option::is_none")]
    pub log_lines: Option<Vec<crate::models::LogLine>>,
}

impl Entry {
    pub fn new() -> Entry {
        Entry {
            meta: None,
            log_lines: None,
        }
    }
}


