/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExecuteSqlStatementCommand {
    #[serde(rename = "appId")]
    pub app_id: uuid::Uuid,
    #[serde(rename = "database")]
    pub database: String,
    #[serde(rename = "default")]
    pub default: bool,
    #[serde(rename = "statement")]
    pub statement: String,
}

impl ExecuteSqlStatementCommand {
    pub fn new(app_id: uuid::Uuid, database: String, default: bool, statement: String) -> ExecuteSqlStatementCommand {
        ExecuteSqlStatementCommand {
            app_id,
            database,
            default,
            statement,
        }
    }
}


