/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetChannelRawLogsVm {
    #[serde(rename = "entries")]
    pub entries: Vec<models::Entry>,
}

impl GetChannelRawLogsVm {
    pub fn new(entries: Vec<models::Entry>) -> GetChannelRawLogsVm {
        GetChannelRawLogsVm {
            entries,
        }
    }
}

