/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetChannelLogsVm {
    #[serde(rename = "logs")]
    pub logs: Vec<String>,
}

impl GetChannelLogsVm {
    pub fn new(logs: Vec<String>) -> GetChannelLogsVm {
        GetChannelLogsVm {
            logs,
        }
    }
}

