/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetChannelRawLogsVm {
    #[serde(rename = "entries")]
    pub entries: Vec<crate::models::Entry>,
}

impl GetChannelRawLogsVm {
    pub fn new(entries: Vec<crate::models::Entry>) -> GetChannelRawLogsVm {
        GetChannelRawLogsVm {
            entries,
        }
    }
}


