/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSqlDatabasesQuery {
    #[serde(rename = "appId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<Option<uuid::Uuid>>,
}

impl GetSqlDatabasesQuery {
    pub fn new() -> GetSqlDatabasesQuery {
        GetSqlDatabasesQuery {
            app_id: None,
        }
    }
}


