/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetVariablesQuery {
    #[serde(rename = "appId")]
    pub app_id: uuid::Uuid,
}

impl GetVariablesQuery {
    pub fn new(app_id: uuid::Uuid) -> GetVariablesQuery {
        GetVariablesQuery {
            app_id,
        }
    }
}


