/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyValueStoreItem {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "links")]
    pub links: Vec<models::ResourceLabel>,
}

impl KeyValueStoreItem {
    pub fn new(name: String, links: Vec<models::ResourceLabel>) -> KeyValueStoreItem {
        KeyValueStoreItem {
            name,
            links,
        }
    }
}

