/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KeyValueStoresList {
    #[serde(rename = "keyValueStores")]
    pub key_value_stores: Vec<crate::models::KeyValueStoreItem>,
}

impl KeyValueStoresList {
    pub fn new(key_value_stores: Vec<crate::models::KeyValueStoreItem>) -> KeyValueStoresList {
        KeyValueStoresList {
            key_value_stores,
        }
    }
}


