/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchAccountDetailsCommand {
    #[serde(rename = "isMarketingEmailOn", skip_serializing_if = "Option::is_none")]
    pub is_marketing_email_on: Option<Box<models::BooleanField>>,
}

impl PatchAccountDetailsCommand {
    pub fn new() -> PatchAccountDetailsCommand {
        PatchAccountDetailsCommand {
            is_marketing_email_on: None,
        }
    }
}

