/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchAppCommand {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Box<models::StringField>>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<Box<models::StringField>>,
}

impl PatchAppCommand {
    pub fn new(id: uuid::Uuid) -> PatchAppCommand {
        PatchAppCommand {
            id,
            domain: None,
            hostname: None,
        }
    }
}

