/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlanItem {
    #[serde(rename = "accountPlanType")]
    pub account_plan_type: String,
    #[serde(rename = "price")]
    pub price: f64,
}

impl PlanItem {
    pub fn new(account_plan_type: String, price: f64) -> PlanItem {
        PlanItem {
            account_plan_type,
            price,
        }
    }
}


