/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Plan {
    #[serde(rename = "accountPlanType", skip_serializing_if = "Option::is_none")]
    pub account_plan_type: Option<crate::models::AccountPlanType>,
    #[serde(rename = "price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price: Option<Option<f64>>,
}

impl Plan {
    pub fn new() -> Plan {
        Plan {
            account_plan_type: None,
            price: None,
        }
    }
}


