/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshTokenCommand {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "refreshToken")]
    pub refresh_token: String,
}

impl RefreshTokenCommand {
    pub fn new(token: String, refresh_token: String) -> RefreshTokenCommand {
        RefreshTokenCommand {
            token,
            refresh_token,
        }
    }
}

