/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RevisionComponentDto {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "route", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub route: Option<Option<String>>,
    #[serde(rename = "channel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
}

impl RevisionComponentDto {
    pub fn new(id: uuid::Uuid, source: String, name: String) -> RevisionComponentDto {
        RevisionComponentDto {
            id,
            source,
            name,
            route: None,
            channel: None,
            r#type: None,
        }
    }
}


