/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDesiredStatusCommand {
    #[serde(rename = "channelId")]
    pub channel_id: uuid::Uuid,
    #[serde(rename = "desiredStatus")]
    pub desired_status: models::DesiredStatus,
}

impl UpdateDesiredStatusCommand {
    pub fn new(channel_id: uuid::Uuid, desired_status: models::DesiredStatus) -> UpdateDesiredStatusCommand {
        UpdateDesiredStatusCommand {
            channel_id,
            desired_status,
        }
    }
}

