/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ValidationStatus {
    #[serde(rename = "InProgress")]
    InProgress,
    #[serde(rename = "Error")]
    Error,
    #[serde(rename = "Ready")]
    Ready,
    #[serde(rename = "Provisioning")]
    Provisioning,

}

impl ToString for ValidationStatus {
    fn to_string(&self) -> String {
        match self {
            Self::InProgress => String::from("InProgress"),
            Self::Error => String::from("Error"),
            Self::Ready => String::from("Ready"),
            Self::Provisioning => String::from("Provisioning"),
        }
    }
}

impl Default for ValidationStatus {
    fn default() -> ValidationStatus {
        Self::InProgress
    }
}




