/**
 * Fermyon Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AccountProvider = 'GitHub' | 'DeviceFlow';

export const AccountProvider = {
    GitHub: 'GitHub' as AccountProvider,
    DeviceFlow: 'DeviceFlow' as AccountProvider
};

