/**
 * Fermyon Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AppEventType = 'Unknown' | 'Create' | 'Update' | 'Delete';

export const AppEventType = {
    Unknown: 'Unknown' as AppEventType,
    Create: 'Create' as AppEventType,
    Update: 'Update' as AppEventType,
    Delete: 'Delete' as AppEventType
};

