/**
 * Fermyon Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppChannelListItem } from './appChannelListItem';
import { ApiHealthStatus } from './apiHealthStatus';
import { AppDomainItem } from './appDomainItem';


export interface AppItem { 
    id: string;
    name: string;
    storageId: string;
    description?: string;
    subdomain: string;
    healthStatus?: ApiHealthStatus;
    channels: Array<AppChannelListItem>;
    domain?: AppDomainItem;
    lastModified: string;
    lastDeployed?: string | null;
    created: string;
    latestRevision?: string | null;
}
export namespace AppItem {
}


