/**
 * Fermyon Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RevisionItem } from './revisionItem';
import { ChannelRevisionSelectionStrategy } from './channelRevisionSelectionStrategy';
import { AppSummaryDto } from './appSummaryDto';
import { EnvironmentVariableItem } from './environmentVariableItem';


export interface ChannelItem { 
    id: string;
    appId: string;
    name: string;
    domain: string;
    revisionSelectionStrategy: ChannelRevisionSelectionStrategy;
    desiredStatus: string;
    activeRevision?: RevisionItem;
    lastPublishAt?: string | null;
    rangeRule?: string | null;
    lastModified?: string;
    appSummary?: AppSummaryDto;
    environmentVariables: Array<EnvironmentVariableItem>;
}
export namespace ChannelItem {
}


