/**
 * Fermyon Cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ValidationStatus = 'InProgress' | 'Error' | 'Ready' | 'Provisioning';

export const ValidationStatus = {
    InProgress: 'InProgress' as ValidationStatus,
    Error: 'Error' as ValidationStatus,
    Ready: 'Ready' as ValidationStatus,
    Provisioning: 'Provisioning' as ValidationStatus
};

