name: GitHub Packages
on:
  push:

jobs:
  publish:
    name: publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" > ~/.npmrc
      - name: publish to GitHub Packages
        run: npm publish
        working-directory: clients/typescript-angular
