name: GitHub Packages
on:
  push:

jobs:
  publish:
    permissions:
      packages: write
    name: publish to GitHub Packages
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${ github.token }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: publish to GitHub Packages
        run: npm publish
        working-directory: clients/typescript-angular
