name: GitHub Packages
on:
  push:

jobs:
  publish:
    permissions:
      packages: write
    name: publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" > ~/.npmrc
      - run: npm install
        working-directory: clients/typescript-angular
      - name: publish to GitHub Packages
        run: npm publish
        working-directory: clients/typescript-angular
